### PR TITLE
More readable README.md and a makefile

### PR DESCRIPTION
**Pull request by DanielAndreasen**
I have updated your markdown syntax for the README, since it was terrible :)
Also added a makefile for doing the installation, test, and clean if necessary.

### CODE REVIEW

**Comment by sousasag** [comment]
The readme was a simple and fast copy paste of the original ares readme. Thanks for the fix.
About the makefile, I forgot about this :) Anyway, this will probably not work for everybody if people have some manual installed libraries the path should be provided.

Thanks ;)

**Comment by DanielAndreasen** [comment]
For the README.md I just saw that the syntax is slightly wrong in section 2 on system requirements. There should be added 2 whitespaces after each of the requirements.

Regarding the makefile, I did not remove the code compilation if the libraries are installed manually.

**Comment by sousasag** [comment]
Just as a note. The slightly wrong sintaxe for the original README.md was purely by chance. I was not aware of the sintaxe for the README :)

**Comment by DanielAndreasen** [comment]
I am not blaming you, just polishing your work :)

**Pull request merged**
